import { CropFamily, CropVariety } from '../types/crops';

export const GLOBAL_CROP_FAMILIES: CropFamily[] = [
  // 1. RICE / PADDY (धान / चावल)
  {
    id: 'rice',
    name: 'Rice / Paddy',
    nameHindi: 'धान / चावल',
    category: 'cereal',
    iconEmoji: '🌾',
    description: 'Primary staple cereal cultivated globally with diverse aromatic, short, and coarse grain types.',
    descriptionHindi: 'विश्व की प्रमुख खाद्यान्न फसल - बासमती, मोटा चावल, छोटा चावल व कनी चावल।',
    varieties: [
      {
        id: 'rice_basmati_1121',
        cropFamilyId: 'rice',
        cropName: 'Rice / Paddy',
        cropHindi: 'धान / चावल',
        varietyName: 'Basmati (Pusa 1121 / 1509)',
        varietyHindi: 'बासमती धान (पूसा 1121 / 1509)',
        category: 'cereal',
        grainType: 'Extra Long Slender Aromatic',
        grainTypeHindi: 'लंबा दाना सुगंधित प्रीमियम बासमती',
        durationDays: 140,
        waterRequirement: 'High',
        waterRequirementHindi: 'अधिक पानी (3-5 सेमी जल भराव)',
        optimalNpkPerAcre: { nitrogenKg: 40, phosphorusKg: 20, potassiumKg: 25, zincKg: 10 },
        targetYieldQuintalPerAcre: 22,
        commonPests: ['Rice Blast (Fungus)', 'Bacterial Leaf Blight', 'Stem Borer'],
        commonPestsHindi: ['झुलसा / ब्लास्ट रोग', 'पत्ती झुलसा', 'तना छेदक कीट'],
        recommendedFertilizerSummary: 'Neem Coated Urea 45 kg + DAP 25 kg + MOP 20 kg per acre in 3 split doses.',
        recommendedFertilizerSummaryHindi: 'नीम लेपित यूरिया 45 किलो + डीएपी 25 किलो + पोटाश 20 किलो प्रति एकड़।',
        simpleAudioHi: 'नमस्ते किसान भाई! आपने बासमती धान चुना है। बासमती में नाइट्रोजन सीमित रखें ताकि पौधे गिरें नहीं। कल्ले फूटते समय यूरिया और पोटाश डालें।',
        simpleAudioEn: 'Hello farmer! You selected Basmati Rice. Keep nitrogen balanced to avoid lodging. Apply urea and potash during tillering and panicle initiation.',
        iconEmoji: '🌾',
      },
      {
        id: 'rice_short_sona',
        cropFamilyId: 'rice',
        cropName: 'Rice / Paddy',
        cropHindi: 'धान / चावल',
        varietyName: 'Short Grain (Sona Masoori / Kolam)',
        varietyHindi: 'छोटा दाना / सोना मसूरी (Short Length)',
        category: 'cereal',
        grainType: 'Medium / Short Slender Grain',
        grainTypeHindi: 'छोटा महीन दाना (डेली टेबल राइस)',
        durationDays: 130,
        waterRequirement: 'High',
        waterRequirementHindi: 'नियमित सिंचाई (वैकल्पिक नमी)',
        optimalNpkPerAcre: { nitrogenKg: 48, phosphorusKg: 25, potassiumKg: 20, zincKg: 8 },
        targetYieldQuintalPerAcre: 28,
        commonPests: ['Brown Plant Hopper', 'Sheath Blight', 'False Smut'],
        commonPestsHindi: ['भूरा फुदका (माहू)', 'शीथ ब्लाइट', 'हल्दी गांठ रोग'],
        recommendedFertilizerSummary: 'Urea 50 kg + DAP 30 kg + Potash 20 kg + Zinc Sulphate 8 kg.',
        recommendedFertilizerSummaryHindi: 'यूरिया 50 किलो + डीएपी 30 किलो + पोटाश 20 किलो + जिंक 8 किलो।',
        simpleAudioHi: 'सोना मसूरी और छोटे दाने के धान में भूरे फुदके और शीथ ब्लाइट का ध्यान रखें। खेत में पानी बदलकर दें और संतुलित डीएपी डालें।',
        simpleAudioEn: 'For Sona Masoori short grain paddy, monitor for brown planthopper and sheath blight. Practice alternate wetting and drying.',
        iconEmoji: '🍚',
      },
      {
        id: 'rice_kani_broken',
        cropFamilyId: 'rice',
        cropName: 'Rice / Paddy',
        cropHindi: 'धान / चावल',
        varietyName: 'Kani Chawal / Short Duration (PR-126)',
        varietyHindi: 'कनी चावल / कम अवधि धान (PR-126 / Broken Rice)',
        category: 'cereal',
        grainType: 'Short Bold / Coarse Milling Grade',
        grainTypeHindi: 'मोटा / कनी दाना (त्वरित 95-105 दिन)',
        durationDays: 105,
        waterRequirement: 'Medium',
        waterRequirementHindi: 'मध्यम पानी (कम पानी में तैयार)',
        optimalNpkPerAcre: { nitrogenKg: 42, phosphorusKg: 22, potassiumKg: 18, zincKg: 10 },
        targetYieldQuintalPerAcre: 30,
        commonPests: ['Leaf Folder', 'Stem Rot'],
        commonPestsHindi: ['पत्ता लपेटक कीट', 'तना सड़न'],
        recommendedFertilizerSummary: 'Fast split: Urea 42 kg + DAP 25 kg in first 35 days.',
        recommendedFertilizerSummaryHindi: 'शुरुआती 35 दिनों में ही यूरिया 42 किलो व डीएपी 25 किलो पूरा कर लें।',
        simpleAudioHi: 'कनी चावल और पीआर-126 जैसी किस्में जल्दी पकती हैं। शुरुआती 30 दिनों में खाद पूरी डाल दें ताकि कम समय में भारी पैदावार मिले।',
        simpleAudioEn: 'Kani Chawal and PR-126 are fast-maturing crops. Complete basal and top-dressing fertilizers in the first 35 days for high yield.',
        iconEmoji: '🥣',
      },
      {
        id: 'rice_high_yield_ir64',
        cropFamilyId: 'rice',
        cropName: 'Rice / Paddy',
        cropHindi: 'धान / चावल',
        varietyName: 'High-Yield Hybrid (IR-64 / Swarna / MTU)',
        varietyHindi: 'उन्नत संकर धान (IR-64 / स्वर्णा / MTU)',
        category: 'cereal',
        grainType: 'Long Bold Commercial Grain',
        grainTypeHindi: 'मजबूत लंबा दाना (उच्च पैदावार)',
        durationDays: 145,
        waterRequirement: 'High',
        waterRequirementHindi: 'अधिक पानी',
        optimalNpkPerAcre: { nitrogenKg: 55, phosphorusKg: 30, potassiumKg: 25, zincKg: 10 },
        targetYieldQuintalPerAcre: 34,
        commonPests: ['Rice Blast', 'Gall Midge', 'Stem Borer'],
        commonPestsHindi: ['ब्लास्ट फफूंद', 'गॉल मिज', 'तना छेदक'],
        recommendedFertilizerSummary: 'Urea 55 kg + DAP 35 kg + MOP 25 kg + Zinc 10 kg.',
        recommendedFertilizerSummaryHindi: 'यूरिया 55 किलो + डीएपी 35 किलो + पोटाश 25 किलो।',
        simpleAudioHi: 'आईआर-64 और संकर धान में भारी पैदावार के लिए फास्फोरस और पोटाश का उचित संतुलन रखें। समय पर सिंचाई दें।',
        simpleAudioEn: 'High-yield hybrid paddy requires robust basal NPK fertilization and continuous moisture during heading stage.',
        iconEmoji: '🌾',
      },
      {
        id: 'rice_jasmine_aromatic',
        cropFamilyId: 'rice',
        cropName: 'Rice / Paddy',
        cropHindi: 'धान / चावल',
        varietyName: 'Jasmine / Fragrant Rice (Hom Mali)',
        varietyHindi: 'जैस्मिन खुशबूदार चावल (Jasmine / Aromatic)',
        category: 'cereal',
        grainType: 'Silky Fragrant Long Grain',
        grainTypeHindi: 'मखमली खुशबूदार चावल',
        durationDays: 125,
        waterRequirement: 'High',
        waterRequirementHindi: 'अधिक पानी',
        optimalNpkPerAcre: { nitrogenKg: 38, phosphorusKg: 20, potassiumKg: 25 },
        targetYieldQuintalPerAcre: 20,
        commonPests: ['Leaf Spot', 'Stem Borer'],
        commonPestsHindi: ['पत्ती धब्बा', 'तना छेदक'],
        recommendedFertilizerSummary: 'Urea 38 kg + Organic Bio-NPK + MOP 25 kg.',
        recommendedFertilizerSummaryHindi: 'यूरिया 38 किलो + जैविक खाद + पोटाश 25 किलो।',
        simpleAudioHi: 'जैस्मिन चावल की सुगंध बनाए रखने के लिए पोटाश और जैविक खाद का अधिक प्रयोग करें।',
        simpleAudioEn: 'For Jasmine rice, supplement with bio-organics and potassium to maintain grain aroma and grain quality.',
        iconEmoji: '🍚',
      },
    ],
  },

  // 2. WHEAT (गेहूं)
  {
    id: 'wheat',
    name: 'Wheat',
    nameHindi: 'गेहूं',
    category: 'cereal',
    iconEmoji: '🌱',
    description: 'Major global Rabi winter cereal crop with bread, durum, and premium golden grain varieties.',
    descriptionHindi: 'प्रमुख रबी खाद्यान्न - शरबती, कठिया (पास्ता) व उच्च पैदावार वाले गेहूं।',
    varieties: [
      {
        id: 'wheat_sharbati',
        cropFamilyId: 'wheat',
        cropName: 'Wheat',
        cropHindi: 'गेहूं',
        varietyName: 'Sharbati Wheat (C-306 / Premium Golden)',
        varietyHindi: 'शरबती गेहूं (सी-306 / सोने जैसा दाना)',
        category: 'cereal',
        grainType: 'Bold Amber Lustrous Grain (High Sweetness)',
        grainTypeHindi: 'चमकदार सुनहरा मीठा दाना (प्रीमियम आटा)',
        durationDays: 135,
        waterRequirement: 'Medium',
        waterRequirementHindi: 'मध्यम पानी (3 से 4 सिंचाई)',
        optimalNpkPerAcre: { nitrogenKg: 40, phosphorusKg: 20, potassiumKg: 15, zincKg: 5 },
        targetYieldQuintalPerAcre: 18,
        commonPests: ['Yellow Rust', 'Loose Smut', 'Aphids (Mahoo)'],
        commonPestsHindi: ['पीला रतुआ (गेरुआ)', 'कंडवा रोग', 'माहू कीट'],
        recommendedFertilizerSummary: 'Neem Coated Urea 40 kg + Single Super Phosphate (SSP) 75 kg + MOP 15 kg.',
        recommendedFertilizerSummaryHindi: 'यूरिया 40 किलो + एसएसपी 75 किलो + पोटाश 15 किलो प्रति एकड़।',
        simpleAudioHi: 'नमस्ते किसान भाई! शरबती गेहूं में बालियां आते समय हल्की सिंचाई करें और पीले रतुए से बचाव के लिए प्रोपिकोनाजोल का छिड़काव करें।',
        simpleAudioEn: 'Hello farmer! For Sharbati Wheat, provide timely light irrigation during crown root initiation and protect against yellow rust.',
        iconEmoji: '🌱',
      },
      {
        id: 'wheat_durum_pasta',
        cropFamilyId: 'wheat',
        cropName: 'Wheat',
        cropHindi: 'गेहूं',
        varietyName: 'Durum / Kathia Wheat (HI 8498 / Malavshakti)',
        varietyHindi: 'कठिया गेहूं / डूरम (HI 8498 / पास्ता व सूजी)',
        category: 'cereal',
        grainType: 'Hard Amber High-Protein Grain',
        grainTypeHindi: 'कठोर दाना, पास्ता-मैकरोनी व सूजी के लिए उत्तम',
        durationDays: 120,
        waterRequirement: 'Low',
        waterRequirementHindi: 'कम पानी (कम सिंचाई में उत्तम)',
        optimalNpkPerAcre: { nitrogenKg: 45, phosphorusKg: 25, potassiumKg: 20 },
        targetYieldQuintalPerAcre: 24,
        commonPests: ['Brown Rust', 'Karnal Bunt'],
        commonPestsHindi: ['भूरा रतुआ', 'करनाल बंट'],
        recommendedFertilizerSummary: 'Urea 45 kg + DAP 25 kg + MOP 20 kg per acre.',
        recommendedFertilizerSummaryHindi: 'यूरिया 45 किलो + डीएपी 25 किलो + पोटाश 20 किलो।',
        simpleAudioHi: 'कठिया और डूरम गेहूं सूखे को आसानी से झेलता है। दाने की चमक बढ़ाने के लिए पहली सिंचाई 21 दिन पर करें।',
        simpleAudioEn: 'Durum pasta wheat is drought-hardy. Apply initial irrigation at 21 days with balanced nitrogen and phosphorus.',
        iconEmoji: '🌾',
      },
      {
        id: 'wheat_high_yield_hd2967',
        cropFamilyId: 'wheat',
        cropName: 'Wheat',
        cropHindi: 'गेहूं',
        varietyName: 'High Yield Bread Wheat (HD-2967 / PBW-343)',
        varietyHindi: 'उन्नत रोटी गेहूं (HD-2967 / PBW-343)',
        category: 'cereal',
        grainType: 'Standard Milling Bread Grain',
        grainTypeHindi: 'रोटी के लिए उत्तम मानक दाना',
        durationDays: 140,
        waterRequirement: 'Medium',
        waterRequirementHindi: 'मध्यम पानी (4 से 5 सिंचाई)',
        optimalNpkPerAcre: { nitrogenKg: 50, phosphorusKg: 25, potassiumKg: 20, zincKg: 8 },
        targetYieldQuintalPerAcre: 26,
        commonPests: ['Stripe Rust', 'Powdery Mildew', 'Termites'],
        commonPestsHindi: ['पीली कुंगी (रतुआ)', 'चूर्णिल आसिता', 'दीमक'],
        recommendedFertilizerSummary: 'Urea 50 kg (split) + DAP 30 kg + MOP 20 kg + Zinc 8 kg.',
        recommendedFertilizerSummaryHindi: 'यूरिया 50 किलो (2 बार में) + डीएपी 30 किलो + पोटाश 20 किलो।',
        simpleAudioHi: 'एचडी 2967 गेहूं में पहली सिंचाई क्राउन रूट निकलने पर 21 दिनों में अवश्य करें। यूरिया दो किस्तों में डालें।',
        simpleAudioEn: 'For HD-2967 wheat, irrigate at Crown Root Initiation stage and apply split urea doses for maximum tillering.',
        iconEmoji: '🌱',
      },
    ],
  },

  // 3. MAIZE / CORN (मक्का)
  {
    id: 'maize',
    name: 'Corn / Maize',
    nameHindi: 'मक्का',
    category: 'cereal',
    iconEmoji: '🌽',
    description: 'High-energy cereal crop encompassing Sweet Corn, Field Grain, Flint, and Baby Corn.',
    descriptionHindi: 'स्वीट कॉर्न, दाना मक्का, बेबी कॉर्न व पॉपकॉर्न किस्में।',
    varieties: [
      {
        id: 'maize_sweet_corn',
        cropFamilyId: 'maize',
        cropName: 'Corn / Maize',
        cropHindi: 'मक्का',
        varietyName: 'Sweet Corn (Sugar 75 / Madhuri)',
        varietyHindi: 'स्वीट कॉर्न / मीठी मक्का (Sugar 75)',
        category: 'cereal',
        grainType: 'Tender Sweet Juicy Kernels',
        grainTypeHindi: 'मुलायम मीठे रसीले दाने (होटल व ताज़ा भुट्टा)',
        durationDays: 80,
        waterRequirement: 'Medium',
        waterRequirementHindi: 'मध्यम पानी (नमी बनाए रखें)',
        optimalNpkPerAcre: { nitrogenKg: 45, phosphorusKg: 25, potassiumKg: 20 },
        targetYieldQuintalPerAcre: 50, // fresh cobs
        commonPests: ['Fall Armyworm (FAW)', 'Stem Borer'],
        commonPestsHindi: ['फॉल आर्मीवर्म (सैनिक कीट)', 'तना छेदक'],
        recommendedFertilizerSummary: 'Urea 45 kg + DAP 30 kg + MOP 20 kg + Humic acid.',
        recommendedFertilizerSummaryHindi: 'यूरिया 45 किलो + डीएपी 30 किलो + पोटाश 20 किलो प्रति एकड़।',
        simpleAudioHi: 'स्वीट कॉर्न में फॉल आर्मीवर्म सुंडी से सावधान रहें। भुट्टा बनते समय नमी कम न होने दें।',
        simpleAudioEn: 'For Sweet Corn, monitor actively for Fall Armyworm and maintain good soil moisture during cob formation.',
        iconEmoji: '🌽',
      },
      {
        id: 'maize_field_yellow',
        cropFamilyId: 'maize',
        cropName: 'Corn / Maize',
        cropHindi: 'मक्का',
        varietyName: 'Hybrid Yellow Dent Corn (Pioneer / Syngenta)',
        varietyHindi: 'पीली संकर मक्का (Pioneer / दाना मक्का)',
        category: 'cereal',
        grainType: 'Hard Dent Grain (Feed & Starch)',
        grainTypeHindi: 'कठोर पीला दाना (पशु आहार व स्टार्च)',
        durationDays: 110,
        waterRequirement: 'Medium',
        waterRequirementHindi: 'मध्यम पानी',
        optimalNpkPerAcre: { nitrogenKg: 60, phosphorusKg: 30, potassiumKg: 25, zincKg: 10 },
        targetYieldQuintalPerAcre: 35,
        commonPests: ['Fall Armyworm', 'Banded Leaf Sheath Blight'],
        commonPestsHindi: ['सैनिक कीट', 'पत्ती झुलसा'],
        recommendedFertilizerSummary: 'Urea 60 kg + DAP 35 kg + MOP 25 kg + Zinc 10 kg.',
        recommendedFertilizerSummaryHindi: 'यूरिया 60 किलो + डीएपी 35 किलो + पोटाश 25 किलो + जिंक 10 किलो।',
        simpleAudioHi: 'पीली संकर मक्का भारी खुराक मांगती है। घुटने की ऊंचाई पर यूरिया की दूसरी खुराक अवश्य दें।',
        simpleAudioEn: 'Hybrid Field Corn requires high nitrogen. Top-dress urea at knee-high and tasseling stages for large cobs.',
        iconEmoji: '🌽',
      },
      {
        id: 'maize_baby_corn',
        cropFamilyId: 'maize',
        cropName: 'Corn / Maize',
        cropHindi: 'मक्का',
        varietyName: 'Baby Corn (G-5414 / High Density)',
        varietyHindi: 'बेबी कॉर्न (G-5414 / छोटी मक्का)',
        category: 'cereal',
        grainType: 'Unfertilized Immature Cob',
        grainTypeHindi: 'बिना परागण वाला कच्चा कोमल भुट्टा',
        durationDays: 60,
        waterRequirement: 'Medium',
        waterRequirementHindi: 'मध्यम पानी (त्वरित 60 दिन)',
        optimalNpkPerAcre: { nitrogenKg: 35, phosphorusKg: 20, potassiumKg: 15 },
        targetYieldQuintalPerAcre: 20,
        commonPests: ['Shoot Fly', 'Aphids'],
        commonPestsHindi: ['प्ररोह मक्खी', 'माहू'],
        recommendedFertilizerSummary: 'Urea 35 kg + DAP 20 kg + MOP 15 kg.',
        recommendedFertilizerSummaryHindi: 'यूरिया 35 किलो + डीएपी 20 किलो + पोटाश 15 किलो।',
        simpleAudioHi: 'बेबी कॉर्न 60 दिन में तैयार हो जाता है। रेशम निकलने के 2 दिन के भीतर तुड़ाई कर लें।',
        simpleAudioEn: 'Baby Corn matures in 60 days. Harvest cobs within 2 days of silk emergence for tender quality.',
        iconEmoji: '🌽',
      },
    ],
  },

  // 4. COTTON (कपास)
  {
    id: 'cotton',
    name: 'Cotton',
    nameHindi: 'कपास (सफेद सोना)',
    category: 'cash_crop',
    iconEmoji: '☁️',
    description: 'Major global fiber cash crop including Bt Hybrid, Organic Desi, and Long Staple cotton.',
    descriptionHindi: 'बी.टी. कपास, देसी कपास व लंबा रेशा (सफेद सोना)।',
    varieties: [
      {
        id: 'cotton_bt_hybrid',
        cropFamilyId: 'cotton',
        cropName: 'Cotton',
        cropHindi: 'कपास',
        varietyName: 'Bt Cotton (Bollgard II Hybrid)',
        varietyHindi: 'बी.टी. कपास (बोलगार्ड 2 हाइब्रिड)',
        category: 'cash_crop',
        grainType: 'Medium-Long Staple Lint',
        grainTypeHindi: 'मध्यम-लंबा रेशा (उच्च लिंट प्रतिशत)',
        durationDays: 165,
        waterRequirement: 'Medium',
        waterRequirementHindi: 'मध्यम पानी (ड्रिप सिंचाई अनुकूल)',
        optimalNpkPerAcre: { nitrogenKg: 50, phosphorusKg: 25, potassiumKg: 30, zincKg: 10 },
        targetYieldQuintalPerAcre: 15,
        commonPests: ['Pink Bollworm', 'Whitefly', 'Thrips', 'Jassids'],
        commonPestsHindi: ['गुलाबी सुंडी', 'सफेद मक्खी', 'थ्रिप्स (चुरडा)', 'हरा तेला'],
        recommendedFertilizerSummary: 'Urea 50 kg + DAP 25 kg + MOP 30 kg + Magnesium Sulphate 10 kg.',
        recommendedFertilizerSummaryHindi: 'यूरिया 50 किलो + डीएपी 25 किलो + पोटाश 30 किलो + मैग्नीशियम 10 किलो।',
        simpleAudioHi: 'कपास में गुलाबी सुंडी और सफेद मक्खी की निगरानी रखें। फूल और टिंडे बनते समय पोटाश और मैग्नीशियम का स्प्रे करें।',
        simpleAudioEn: 'In Bt Cotton, install pheromone traps for pink bollworm and spray foliar potassium to prevent leaf reddening.',
        iconEmoji: '☁️',
      },
      {
        id: 'cotton_desi_organic',
        cropFamilyId: 'cotton',
        cropName: 'Cotton',
        cropHindi: 'कपास',
        varietyName: 'Desi Indigenous Cotton (Arboreum)',
        varietyHindi: 'देसी जैविक कपास (हर्बेशियम / रोगरोधी)',
        category: 'cash_crop',
        grainType: 'Short Coarse Native Fiber',
        grainTypeHindi: 'मजबूत छोटा रेशा (कम लागत में उत्तम)',
        durationDays: 145,
        waterRequirement: 'Low',
        waterRequirementHindi: 'कम पानी (सूखा सहनशील)',
        optimalNpkPerAcre: { nitrogenKg: 30, phosphorusKg: 15, potassiumKg: 15 },
        targetYieldQuintalPerAcre: 10,
        commonPests: ['Sucking Pests (Mild)', 'Grey Mildew'],
        commonPestsHindi: ['रस चूसक कीट', 'धूसर फफूंद'],
        recommendedFertilizerSummary: 'Farmyard Manure (FYM) 2 tons + Urea 30 kg + SSP 50 kg.',
        recommendedFertilizerSummaryHindi: 'गोबर की सड़ी खाद 2 टन + यूरिया 30 किलो + एसएसपी 50 किलो।',
        simpleAudioHi: 'देसी कपास सूखे को आसानी से सहती है। इसमें रासायनिक कीटनाशक की कम जरूरत होती है, नीम तेल का प्रयोग करें।',
        simpleAudioEn: 'Desi organic cotton is drought-tolerant and pest-resistant. Use neem-based sprays for pest control.',
        iconEmoji: '☁️',
      },
    ],
  },

  // 5. SUGARCANE (गन्ना)
  {
    id: 'sugarcane',
    name: 'Sugarcane',
    nameHindi: 'गन्ना',
    category: 'cash_crop',
    iconEmoji: '🎋',
    description: 'Perennial tropical sucrose crop with early-maturing and drought-resilient varieties.',
    descriptionHindi: 'अगेती व पछेती गन्ना किस्में (Co 0238, Co 86032)।',
    varieties: [
      {
        id: 'sugarcane_co0238',
        cropFamilyId: 'sugarcane',
        cropName: 'Sugarcane',
        cropHindi: 'गन्ना',
        varietyName: 'Early Maturing High Sugar (Co 0238 / Karan-4)',
        varietyHindi: 'अगेती उच्च शर्करा गन्ना (Co 0238)',
        category: 'cash_crop',
        grainType: 'High Sucrose Juicy Thick Cane',
        grainTypeHindi: 'मोटा रसदार गन्ना (12.5% रिकवरी)',
        durationDays: 330,
        waterRequirement: 'High',
        waterRequirementHindi: 'अधिक पानी (नियमित सिंचाई)',
        optimalNpkPerAcre: { nitrogenKg: 80, phosphorusKg: 35, potassiumKg: 40, zincKg: 15 },
        targetYieldQuintalPerAcre: 400,
        commonPests: ['Red Rot (Fungus)', 'Top Borer', 'Pyrilla'],
        commonPestsHindi: ['लाल सड़न रोग (रेड रॉट)', 'चोटी छेदक', 'पायरीला कीट'],
        recommendedFertilizerSummary: 'Urea 80 kg + DAP 40 kg + MOP 40 kg + Zinc 15 kg in 4 split doses.',
        recommendedFertilizerSummaryHindi: 'यूरिया 80 किलो + डीएपी 40 किलो + पोटाश 40 किलो प्रति एकड़।',
        simpleAudioHi: 'गन्ने की Co 0238 किस्म में लाल सड़न रोग से बचाव के लिए बीज का उपचार करें और पोटाश खाद समय पर दें।',
        simpleAudioEn: 'For Co 0238 sugarcane, treat setts against red rot and apply balanced potash to increase cane sucrose.',
        iconEmoji: '🎋',
      },
      {
        id: 'sugarcane_co86032',
        cropFamilyId: 'sugarcane',
        cropName: 'Sugarcane',
        cropHindi: 'गन्ना',
        varietyName: 'Drought Resilient Tropical (Co 86032 / Nayan)',
        varietyHindi: 'सूखा रोधी दक्षिण गन्ना (Co 86032)',
        category: 'cash_crop',
        grainType: 'Heavy Cane Weight & Solid Stalk',
        grainTypeHindi: 'ठोस भारी गन्ना, रतून (पेड़ी) के लिए उत्तम',
        durationDays: 360,
        waterRequirement: 'Medium',
        waterRequirementHindi: 'मध्यम पानी',
        optimalNpkPerAcre: { nitrogenKg: 75, phosphorusKg: 30, potassiumKg: 45 },
        targetYieldQuintalPerAcre: 450,
        commonPests: ['Internode Borer', 'Woolly Aphid'],
        commonPestsHindi: ['पोर छेदक सुंडी', 'सफेद रोयेंदार माहू'],
        recommendedFertilizerSummary: 'Urea 75 kg + SSP 100 kg + MOP 45 kg + Bio-fertilizer.',
        recommendedFertilizerSummaryHindi: 'यूरिया 75 किलो + एसएसपी 100 किलो + पोटाश 45 किलो।',
        simpleAudioHi: 'Co 86032 गन्ना सूखा सहन कर लेता है और पेड़ी फसल में भी शानदार वजन देता है।',
        simpleAudioEn: 'Co 86032 performs well under low-water conditions and produces high ratoon yields.',
        iconEmoji: '🎋',
      },
    ],
  },

  // 6. PULSES / LEGUMES (दालें)
  {
    id: 'pulses',
    name: 'Pulses & Legumes',
    nameHindi: 'दालें व दलहन',
    category: 'pulse',
    iconEmoji: '🫘',
    description: 'Nitrogen-fixing protein crops: Chickpea, Pigeon Pea, Green Gram, Black Gram, Lentil.',
    descriptionHindi: 'चना (देसी व काबुली), अरहर, मूंग, उड़द व मसूर।',
    varieties: [
      {
        id: 'pulse_chickpea_desi',
        cropFamilyId: 'pulses',
        cropName: 'Chickpea / Gram',
        cropHindi: 'चना / छोले',
        varietyName: 'Desi Bengal Gram (JG-11 / Vishal)',
        varietyHindi: 'देसी चना (JG-11 / विशाल)',
        category: 'pulse',
        grainType: 'Brown Angular High Protein Seed',
        grainTypeHindi: 'भूरा दाना (दाल व बेसन के लिए उत्तम)',
        durationDays: 110,
        waterRequirement: 'Low',
        waterRequirementHindi: 'कम पानी (1 से 2 सिंचाई)',
        optimalNpkPerAcre: { nitrogenKg: 10, phosphorusKg: 25, potassiumKg: 10, zincKg: 5 },
        targetYieldQuintalPerAcre: 10,
        commonPests: ['Pod Borer (Helicoverpa)', 'Fusarium Wilt', 'Dry Root Rot'],
        commonPestsHindi: ['इल्ली (फली छेदक)', 'उकठा रोग (मुरझान)', 'जड़ सड़न'],
        recommendedFertilizerSummary: 'DAP 25 kg + SSP 50 kg + Rhizobium bio-culture (Low Nitrogen).',
        recommendedFertilizerSummaryHindi: 'डीएपी 25 किलो + एसएसपी 50 किलो + राइजोबियम कल्चर (यूरिया कम डालें)।',
        simpleAudioHi: 'चने में अधिक यूरिया न डालें क्योंकि पौधा हवा से नाइट्रोजन खुद बनाता है। फली छेदक इल्ली के लिए फेरोमोन ट्रैप लगाएं।',
        simpleAudioEn: 'In chickpea, avoid excess urea as roots fix nitrogen. Monitor for pod borer caterpillars with pheromone traps.',
        iconEmoji: '🫘',
      },
      {
        id: 'pulse_kabuli_dollar',
        cropFamilyId: 'pulses',
        cropName: 'Chickpea / Gram',
        cropHindi: 'चना / छोले',
        varietyName: 'Kabuli Chickpea / Dollar Chana (KAK-2 / PKV-4)',
        varietyHindi: 'काबुली चना / डॉलर चना (बड़ा सफेद दाना)',
        category: 'pulse',
        grainType: 'Extra Large Creamish White Grain',
        grainTypeHindi: 'बड़ा सफेद दाना (उच्च बाज़ार भाव)',
        durationDays: 105,
        waterRequirement: 'Medium',
        waterRequirementHindi: 'मध्यम पानी (उचित जल निकास)',
        optimalNpkPerAcre: { nitrogenKg: 12, phosphorusKg: 30, potassiumKg: 15 },
        targetYieldQuintalPerAcre: 12,
        commonPests: ['Pod Borer', 'Collar Rot'],
        commonPestsHindi: ['फली छेदक सुंडी', 'तना सड़न'],
        recommendedFertilizerSummary: 'DAP 30 kg + Potash 15 kg + Sulphur 5 kg.',
        recommendedFertilizerSummaryHindi: 'डीएपी 30 किलो + पोटाश 15 किलो + सल्फर 5 किलो।',
        simpleAudioHi: 'डॉलर काबुली चने में पानी का भराव न होने दें। फूल आते समय सिंचाई न करें, फलियां बनते समय करें।',
        simpleAudioEn: 'For Kabuli Dollar Chana, ensure sharp drainage and irrigate during pod-filling stage rather than flowering.',
        iconEmoji: '🫘',
      },
      {
        id: 'pulse_pigeonpea_arhar',
        cropFamilyId: 'pulses',
        cropName: 'Pigeon Pea / Arhar',
        cropHindi: 'अरहर / तुअर दाल',
        varietyName: 'Pigeon Pea / Tur (BDN-711 / Asha / Maruti)',
        varietyHindi: 'अरहर दाल (BDN-711 / आशा / मारुति)',
        category: 'pulse',
        grainType: 'Bold Red-Brown Lentil Grain',
        grainTypeHindi: 'मोटा लाल-भूरा दाना (दाल के लिए)',
        durationDays: 160,
        waterRequirement: 'Low',
        waterRequirementHindi: 'कम पानी (गहरी जड़ें)',
        optimalNpkPerAcre: { nitrogenKg: 12, phosphorusKg: 25, potassiumKg: 12 },
        targetYieldQuintalPerAcre: 10,
        commonPests: ['Pod Borer', 'Sterility Mosaic Disease', 'Phytophthora Blight'],
        commonPestsHindi: ['फली छेदक', 'बांझपन रोग', 'झुलसा रोग'],
        recommendedFertilizerSummary: 'DAP 25 kg + Potash 12 kg + Gypsum 50 kg.',
        recommendedFertilizerSummaryHindi: 'डीएपी 25 किलो + पोटाश 12 किलो + जिप्सम 50 किलो।',
        simpleAudioHi: 'अरहर में जिप्सम और सल्फर डालने से दाल में प्रोटीन और चमक बढ़ती है। फली बनते समय इल्ली पर नजर रखें।',
        simpleAudioEn: 'Applying gypsum in pigeon pea improves grain protein and pod development. Treat for pod borers at flowering.',
        iconEmoji: '🫘',
      },
      {
        id: 'pulse_moong_greengram',
        cropFamilyId: 'pulses',
        cropName: 'Green Gram / Moong',
        cropHindi: 'मूंग दाल',
        varietyName: 'Green Gram (Pusa Vishal / Samrat / IPM-205)',
        varietyHindi: 'मूंग दाल (पूसा विशाल / सम्राट - 60 दिन)',
        category: 'pulse',
        grainType: 'Bright Green Medium Grain',
        grainTypeHindi: 'चमकदार हरा दाना (जायद व खरीफ 60 दिन)',
        durationDays: 60,
        waterRequirement: 'Low',
        waterRequirementHindi: 'कम पानी',
        optimalNpkPerAcre: { nitrogenKg: 8, phosphorusKg: 20, potassiumKg: 10 },
        targetYieldQuintalPerAcre: 6,
        commonPests: ['Yellow Mosaic Virus (YMV)', 'Whitefly', 'Thrips'],
        commonPestsHindi: ['पीला मोज़ेक वायरस', 'सफेद मक्खी', 'थ्रिप्स'],
        recommendedFertilizerSummary: 'DAP 20 kg + Sulphur 5 kg.',
        recommendedFertilizerSummaryHindi: 'डीएपी 20 किलो + सल्फर 5 किलो।',
        simpleAudioHi: 'मूंग केवल 60 दिन में पक जाती है। सफेद मक्खी को रोकें ताकि पीला मोज़ेक वायरस न फैले।',
        simpleAudioEn: 'Moong matures in just 60 days. Control whitefly to prevent Yellow Mosaic Virus.',
        iconEmoji: '🫘',
      },
    ],
  },

  // 7. SOYBEAN (सोयाबीन)
  {
    id: 'soybean',
    name: 'Soybean',
    nameHindi: 'सोयाबीन',
    category: 'oilseed',
    iconEmoji: '🌱',
    description: 'Premier protein and vegetable oilseed crop (JS 335, JS 9560, NRC 37).',
    descriptionHindi: 'प्रमुख तिलहन व प्रोटीन फसल - JS 335 व 9560।',
    varieties: [
      {
        id: 'soybean_js9560',
        cropFamilyId: 'soybean',
        cropName: 'Soybean',
        cropHindi: 'सोयाबीन',
        varietyName: 'Early 85-Day Drought Resilient (JS 9560)',
        varietyHindi: 'अगेती सूखा रोधी सोयाबीन (JS 9560 - 85 दिन)',
        category: 'oilseed',
        grainType: 'Yellow Spherical High Oil Seed',
        grainTypeHindi: 'पीला गोल दाना (त्वरित 85 दिन)',
        durationDays: 85,
        waterRequirement: 'Medium',
        waterRequirementHindi: 'मध्यम पानी (वर्षा आधारित)',
        optimalNpkPerAcre: { nitrogenKg: 15, phosphorusKg: 30, potassiumKg: 15, zincKg: 5 },
        targetYieldQuintalPerAcre: 10,
        commonPests: ['Girdle Beetle', 'Semilooper', 'Yellow Mosaic'],
        commonPestsHindi: ['गर्डल बीटल (चक्र भृंग)', 'अर्धकुंडलक इल्ली', 'पीला मोज़ेक'],
        recommendedFertilizerSummary: 'DAP 30 kg + MOP 15 kg + Single Super Phosphate 50 kg.',
        recommendedFertilizerSummaryHindi: 'डीएपी 30 किलो + पोटाश 15 किलो + सिंगल सुपर फास्फेट 50 किलो।',
        simpleAudioHi: 'JS 9560 सोयाबीन 85 दिन में आ जाती है। गर्डल बीटल से बचाव के लिए शुरुआती 30 दिन में क्लोरेंट्रानिलिप्रोल का छिड़काव करें।',
        simpleAudioEn: 'JS 9560 soybean matures early in 85 days. Watch for girdle beetle at 30 days and apply phosphorus for root nodules.',
        iconEmoji: '🌱',
      },
      {
        id: 'soybean_js335',
        cropFamilyId: 'soybean',
        cropName: 'Soybean',
        cropHindi: 'सोयाबीन',
        varietyName: 'Standard High Yield (JS 335 / NRC 37)',
        varietyHindi: 'मानक उच्च पैदावार सोयाबीन (JS 335 / NRC 37)',
        category: 'oilseed',
        grainType: 'Medium Yellow Seed (High Protein)',
        grainTypeHindi: 'मध्यम पीला दाना (उच्च प्रोटीन व तेल)',
        durationDays: 100,
        waterRequirement: 'Medium',
        waterRequirementHindi: 'मध्यम पानी',
        optimalNpkPerAcre: { nitrogenKg: 18, phosphorusKg: 35, potassiumKg: 20, zincKg: 8 },
        targetYieldQuintalPerAcre: 12,
        commonPests: ['Tobacco Caterpillar (Spodoptera)', 'Anthracnose'],
        commonPestsHindi: ['तंबाकू की इल्ली', 'एंथ्रेक्नोज फफूंद'],
        recommendedFertilizerSummary: 'DAP 35 kg + MOP 20 kg + Sulphur 10 kg + Zinc 8 kg.',
        recommendedFertilizerSummaryHindi: 'डीएपी 35 किलो + पोटाश 20 किलो + सल्फर 10 किलो।',
        simpleAudioHi: 'सोयाबीन में सल्फर डालने से तेल की मात्रा बढ़ती है। जल भराव से खेत को बचाएं।',
        simpleAudioEn: 'Adding sulphur to soybean increases oil content. Ensure good field drainage during monsoon downpours.',
        iconEmoji: '🌱',
      },
    ],
  },

  // 8. MILLETS / SHREE ANNA (मोटा अनाज / मिलेट्स)
  {
    id: 'millets',
    name: 'Millets / Shree Anna',
    nameHindi: 'मिलेट्स / श्री अन्न (मोटा अनाज)',
    category: 'millet',
    iconEmoji: '🌾',
    description: 'Climate-resilient superfoods: Pearl Millet (Bajra), Finger Millet (Ragi), Sorghum (Jowar).',
    descriptionHindi: 'जलवायु अनुकूल पोषक अनाज - बाजरा, रागी, ज्वार व कंगनी।',
    varieties: [
      {
        id: 'millet_pearl_bajra',
        cropFamilyId: 'millets',
        cropName: 'Pearl Millet / Bajra',
        cropHindi: 'बाजरा',
        varietyName: 'Hybrid Pearl Millet (HHB 67 / Pioneer 86M88)',
        varietyHindi: 'संकर बाजरा (HHB 67 / 86M88)',
        category: 'millet',
        grainType: 'Greyish Pearl Nutritious Grain',
        grainTypeHindi: 'धूसर दाना (आयरन व जिंक से भरपूर)',
        durationDays: 75,
        waterRequirement: 'Low',
        waterRequirementHindi: 'बहुत कम पानी (सूखे में भी उत्तम)',
        optimalNpkPerAcre: { nitrogenKg: 30, phosphorusKg: 15, potassiumKg: 10 },
        targetYieldQuintalPerAcre: 16,
        commonPests: ['Downy Mildew (Green Ear)', 'Ergot Fungus', 'Shoot Fly'],
        commonPestsHindi: ['जोगिया रोग (ग्रीन ईयर)', 'अरगट रोग', 'तना मक्खी'],
        recommendedFertilizerSummary: 'Urea 30 kg + DAP 15 kg in dryland conditions.',
        recommendedFertilizerSummaryHindi: 'यूरिया 30 किलो + डीएपी 15 किलो प्रति एकड़।',
        simpleAudioHi: 'बाजरा कम पानी और तेज धूप में भी अच्छी पैदावार देता है। जोगिया रोग से बचाव के लिए बीज शोधन अवश्य करें।',
        simpleAudioEn: 'Pearl Millet thrives in arid, high-temperature conditions. Treat seeds with metalaxyl against downy mildew.',
        iconEmoji: '🌾',
      },
      {
        id: 'millet_finger_ragi',
        cropFamilyId: 'millets',
        cropName: 'Finger Millet / Ragi',
        cropHindi: 'रागी / मडुआ',
        varietyName: 'Finger Millet (GPU 28 / ML 365 / KMR 204)',
        varietyHindi: 'रागी / मडुआ (GPU 28 / ML 365 - कैल्शियम भरपूर)',
        category: 'millet',
        grainType: 'Small Reddish Brown Seed (High Calcium)',
        grainTypeHindi: 'छोटा लाल-भूरा दाना (कैल्शियम का खजाना)',
        durationDays: 115,
        waterRequirement: 'Low',
        waterRequirementHindi: 'कम पानी',
        optimalNpkPerAcre: { nitrogenKg: 25, phosphorusKg: 15, potassiumKg: 15 },
        targetYieldQuintalPerAcre: 15,
        commonPests: ['Ragi Blast (Pyricularia)', 'Aphids'],
        commonPestsHindi: ['रागी ब्लास्ट', 'माहू'],
        recommendedFertilizerSummary: 'Urea 25 kg + DAP 15 kg + Potash 15 kg.',
        recommendedFertilizerSummaryHindi: 'यूरिया 25 किलो + डीएपी 15 किलो + पोटाश 15 किलो।',
        simpleAudioHi: 'रागी स्वास्थ्य के लिए सर्वोत्तम है। ब्लास्ट रोग से बचाव के लिए ट्राइसाइक्लाजोल का हल्का छिड़काव करें।',
        simpleAudioEn: 'Finger Millet is a calcium-rich superfood. Guard against ragi blast with preventive bio-fungicides.',
        iconEmoji: '🌾',
      },
      {
        id: 'millet_sorghum_jowar',
        cropFamilyId: 'millets',
        cropName: 'Sorghum / Jowar',
        cropHindi: 'ज्वार',
        varietyName: 'Grain Sorghum (Maldandi M35-1 / CSH-14)',
        varietyHindi: 'मालदंडी ज्वार (M35-1 / CSH-14 - सफेद चमकदार दाना)',
        category: 'millet',
        grainType: 'Pearly White Bold Sweet Grain',
        grainTypeHindi: 'मोती जैसा सफेद दाना (मीठी रोटी व चारा)',
        durationDays: 120,
        waterRequirement: 'Low',
        waterRequirementHindi: 'कम पानी',
        optimalNpkPerAcre: { nitrogenKg: 35, phosphorusKg: 20, potassiumKg: 15 },
        targetYieldQuintalPerAcre: 18,
        commonPests: ['Shoot Fly', 'Stem Borer', 'Grain Mold'],
        commonPestsHindi: ['प्ररोह मक्खी', 'तना छेदक', 'दाना फफूंद'],
        recommendedFertilizerSummary: 'Urea 35 kg + DAP 20 kg + Potash 15 kg.',
        recommendedFertilizerSummaryHindi: 'यूरिया 35 किलो + डीएपी 20 किलो + पोटाश 15 किलो।',
        simpleAudioHi: 'मालदंडी ज्वार की रोटी स्वादिष्ट और पौष्टिक होती है। बुवाई के तुरंत बाद तना मक्खी से बचाव करें।',
        simpleAudioEn: 'Maldandi Jowar yields premium grains. Protect early seedlings against shoot fly with imidacloprid seed treatment.',
        iconEmoji: '🌾',
      },
    ],
  },

  // 9. MUSTARD & OILSEEDS (सरसों व तिलहन)
  {
    id: 'mustard',
    name: 'Mustard & Rapeseed',
    nameHindi: 'सरसों व तोरिया',
    category: 'oilseed',
    iconEmoji: '🌼',
    description: 'Major winter oilseed crop (Pusa Bold, Giriraj, Yellow Mustard).',
    descriptionHindi: 'पीली व काली सरसों, राई व तोरिया।',
    varieties: [
      {
        id: 'mustard_pusa_bold',
        cropFamilyId: 'mustard',
        cropName: 'Mustard / Rapeseed',
        cropHindi: 'सरसों',
        varietyName: 'Black Mustard (Pusa Bold / Giriraj / RH-749)',
        varietyHindi: 'काली सरसों (पूसा बोल्ड / गिरिराज / RH-749)',
        category: 'oilseed',
        grainType: 'Bold Dark Brown Seed (42% Oil Content)',
        grainTypeHindi: 'मोटा काला-भूरा दाना (42% तेल मात्रा)',
        durationDays: 130,
        waterRequirement: 'Low',
        waterRequirementHindi: 'कम पानी (2 हल्की सिंचाई)',
        optimalNpkPerAcre: { nitrogenKg: 35, phosphorusKg: 18, potassiumKg: 15, zincKg: 5 },
        targetYieldQuintalPerAcre: 10,
        commonPests: ['Mustard Aphid (Chetpa/Mahoo)', 'White Rust', 'Alternaria Blight'],
        commonPestsHindi: ['माहू (चेपा कीट)', 'सफेद रतुआ', 'अल्टरनेरिया झुलसा'],
        recommendedFertilizerSummary: 'Urea 35 kg + SSP 60 kg + Potash 15 kg + Sulphur 10 kg (Essential for oil).',
        recommendedFertilizerSummaryHindi: 'यूरिया 35 किलो + एसएसपी 60 किलो + पोटाश 15 किलो + सल्फर 10 किलो (तेल के लिए जरूरी)।',
        simpleAudioHi: 'सरसों में सल्फर खाद डालने से तेल का प्रतिशत और तीखापन बढ़ता है। जनवरी में माहू कीट पर विशेष नजर रखें।',
        simpleAudioEn: 'Applying sulphur in mustard significantly boosts oil percentage. Monitor for mustard aphids in cool weather.',
        iconEmoji: '🌼',
      },
      {
        id: 'mustard_yellow_pusa',
        cropFamilyId: 'mustard',
        cropName: 'Mustard / Rapeseed',
        cropHindi: 'सरसों',
        varietyName: 'Yellow Mustard (Pusa Gold / YSH-401)',
        varietyHindi: 'पीली सरसों (पूसा गोल्ड / YSH-401 - प्रीमियम तेल)',
        category: 'oilseed',
        grainType: 'Golden Yellow Mild Seed',
        grainTypeHindi: 'सुनहरा पीला दाना (पारदर्शी मीठा तेल)',
        durationDays: 115,
        waterRequirement: 'Low',
        waterRequirementHindi: 'कम पानी',
        optimalNpkPerAcre: { nitrogenKg: 30, phosphorusKg: 15, potassiumKg: 12 },
        targetYieldQuintalPerAcre: 8,
        commonPests: ['Aphids', 'Downy Mildew'],
        commonPestsHindi: ['माहू कीट', 'मृदुरोमिल फफूंद'],
        recommendedFertilizerSummary: 'Urea 30 kg + DAP 15 kg + Potash 12 kg + Sulphur 8 kg.',
        recommendedFertilizerSummaryHindi: 'यूरिया 30 किलो + डीएपी 15 किलो + पोटाश 12 किलो + सल्फर 8 किलो।',
        simpleAudioHi: 'पीली सरसों का तेल बाजार में ऊंचे दाम पर बिकता है। फूल आते समय सिंचाई न करें।',
        simpleAudioEn: 'Yellow mustard commands higher market prices for pure cooking oil. Avoid flooding during peak flowering.',
        iconEmoji: '🌼',
      },
    ],
  },

  // 10. POTATO (आलू)
  {
    id: 'potato',
    name: 'Potato',
    nameHindi: 'आलू',
    category: 'vegetable',
    iconEmoji: '🥔',
    description: 'High-value tuber vegetable encompassing table, processing chips, and early harvest varieties.',
    descriptionHindi: 'कुफरी ज्योति, चिपसोना (चिप्स वाला) व कुफरी पुखराज।',
    varieties: [
      {
        id: 'potato_kufri_jyoti',
        cropFamilyId: 'potato',
        cropName: 'Potato',
        cropHindi: 'आलू',
        varietyName: 'Table Potato (Kufri Jyoti / Kufri Bahar)',
        varietyHindi: 'सब्जी आलू (कुफरी ज्योति / कुफरी बहार)',
        category: 'vegetable',
        grainType: 'Oval Creamish Smooth Tuber',
        grainTypeHindi: 'चिकना अंडाकार कंद (रसोई के लिए)',
        durationDays: 100,
        waterRequirement: 'High',
        waterRequirementHindi: 'नियमित पानी (हल्की नमी)',
        optimalNpkPerAcre: { nitrogenKg: 70, phosphorusKg: 40, potassiumKg: 50 },
        targetYieldQuintalPerAcre: 120,
        commonPests: ['Late Blight (Phytophthora)', 'Early Blight', 'Potato Tuber Moth'],
        commonPestsHindi: ['पिछेता झुलसा (लेट ब्लाइट)', 'अगेती झुलसा', 'कंद शलभ'],
        recommendedFertilizerSummary: 'Urea 70 kg + DAP 45 kg + MOP 50 kg + Zinc Sulphate 10 kg.',
        recommendedFertilizerSummaryHindi: 'यूरिया 70 किलो + डीएपी 45 किलो + पोटाश 50 किलो प्रति एकड़।',
        simpleAudioHi: 'आलू में पोटाश डालने से कंद का आकार और वजन बढ़ता है। कोहरा पड़ने पर पिछेता झुलसा से बचाव के लिए मेंकोजेब का छिड़काव करें।',
        simpleAudioEn: 'Potassium is vital for large potato tubers. Spray mancozeb or metalaxyl proactively during cloudy foggy weather against late blight.',
        iconEmoji: '🥔',
      },
      {
        id: 'potato_kufri_chipsona',
        cropFamilyId: 'potato',
        cropName: 'Potato',
        cropHindi: 'आलू',
        varietyName: 'Processing Chips Grade (Kufri Chipsona 1 & 3)',
        varietyHindi: 'चिपसोना आलू (Kufri Chipsona 1 & 3 - चिप्स व वेफर्स)',
        category: 'vegetable',
        grainType: 'High Dry Matter Low Sugar White Flesh',
        grainTypeHindi: 'कम शर्करा सफेद गूदा (चिप्स तलने पर लाल नहीं होता)',
        durationDays: 110,
        waterRequirement: 'High',
        waterRequirementHindi: 'नियमित हल्की सिंचाई',
        optimalNpkPerAcre: { nitrogenKg: 75, phosphorusKg: 45, potassiumKg: 60 },
        targetYieldQuintalPerAcre: 140,
        commonPests: ['Late Blight', 'Bacterial Wilt'],
        commonPestsHindi: ['झुलसा रोग', 'जीवाणु मुरझान'],
        recommendedFertilizerSummary: 'Urea 75 kg + DAP 50 kg + MOP 60 kg (High Potash for solids).',
        recommendedFertilizerSummaryHindi: 'यूरिया 75 किलो + डीएपी 50 किलो + पोटाश 60 किलो (सॉलिड बढ़ाने के लिए)।',
        simpleAudioHi: 'चिपसोना आलू में पोटाश की मात्रा ज्यादा रखें ताकि कंद में सूखा पदार्थ बने और चिप्स कुरकुरे बनें।',
        simpleAudioEn: 'Chipsona processing potatoes require heavy potassium application to maximize dry matter and prevent frying discoloration.',
        iconEmoji: '🥔',
      },
    ],
  },

  // 11. TOMATO (टमाटर)
  {
    id: 'tomato',
    name: 'Tomato',
    nameHindi: 'टमाटर',
    category: 'vegetable',
    iconEmoji: '🍅',
    description: 'High-value horticultural vegetable crop: Hybrid Salad, Plum Paste, and Cherry Tomatoes.',
    descriptionHindi: 'संकर अभिनव, रोमा प्लम व चेरी टमाटर।',
    varieties: [
      {
        id: 'tomato_hybrid_abhinav',
        cropFamilyId: 'tomato',
        cropName: 'Tomato',
        cropHindi: 'टमाटर',
        varietyName: 'Commercial Hybrid (Abhinav / US-440 / Arka Rakshak)',
        varietyHindi: 'संकर टमाटर (अभिनव / US-440 / अर्का रक्षक)',
        category: 'vegetable',
        grainType: 'Firm Glossy Deep Red Fruit (Long Shelf Life)',
        grainTypeHindi: 'ठोस गहरा लाल फल (लंबे समय तक ताज़ा)',
        durationDays: 130,
        waterRequirement: 'High',
        waterRequirementHindi: 'नियमित ड्रिप सिंचाई',
        optimalNpkPerAcre: { nitrogenKg: 60, phosphorusKg: 35, potassiumKg: 45, zincKg: 5 },
        targetYieldQuintalPerAcre: 180,
        commonPests: ['Tomato Leaf Curl Virus (TLCV)', 'Fruit Borer (Helicoverpa)', 'Early/Late Blight'],
        commonPestsHindi: ['पत्ता मरोड़ वायरस (TLCV)', 'फल छेदक इल्ली', 'अगेती/पिछेता झुलसा'],
        recommendedFertilizerSummary: 'Urea 60 kg + DAP 35 kg + MOP 45 kg + Calcium Nitrate 15 kg + Boron 2 kg.',
        recommendedFertilizerSummaryHindi: 'यूरिया 60 किलो + डीएपी 35 किलो + पोटाश 45 किलो + कैल्शियम नाइट्रेट 15 किलो + बोरॉन 2 किलो।',
        simpleAudioHi: 'टमाटर में फल फटने से रोकने के लिए बोरॉन और कैल्शियम नाइट्रेट का छिड़काव करें। सफेद मक्खी से पत्ता मरोड़ वायरस को रोकें।',
        simpleAudioEn: 'In tomato, spray calcium nitrate and boron to prevent blossom end rot and fruit cracking. Control whiteflies to stop leaf curl virus.',
        iconEmoji: '🍅',
      },
    ],
  },

  // 12. ONION & GARLIC (प्याज़ व लहसुन)
  {
    id: 'onion_garlic',
    name: 'Onion & Garlic',
    nameHindi: 'प्याज़ व लहसुन',
    category: 'vegetable',
    iconEmoji: '🧅',
    description: 'Essential culinary bulb crops (Nasik Red, Bhima Super, White Onion, Garlic).',
    descriptionHindi: 'नासिक लाल प्याज़, सफेद प्याज़ व लहसुन।',
    varieties: [
      {
        id: 'onion_nasik_red',
        cropFamilyId: 'onion_garlic',
        cropName: 'Onion & Garlic',
        cropHindi: 'प्याज़ व लहसुन',
        varietyName: 'Red Onion (Nasik Red / Bhima Super / N-53)',
        varietyHindi: 'लाल प्याज़ (नासिक रेड / भीमा सुपर / N-53)',
        category: 'vegetable',
        grainType: 'Globe Shaped Pungent Red Bulb',
        grainTypeHindi: 'गोल तीखा लाल कंद (उत्तम भंडारण क्षमता)',
        durationDays: 120,
        waterRequirement: 'Medium',
        waterRequirementHindi: 'मध्यम पानी (हल्की बारंबार सिंचाई)',
        optimalNpkPerAcre: { nitrogenKg: 45, phosphorusKg: 25, potassiumKg: 35, zincKg: 8 },
        targetYieldQuintalPerAcre: 100,
        commonPests: ['Onion Thrips', 'Purple Blotch (Alternaria)', 'Basal Rot'],
        commonPestsHindi: ['प्याज़ का थ्रिप्स कीट', 'बैंगनी धब्बा रोग', 'जड़ सड़न'],
        recommendedFertilizerSummary: 'Urea 45 kg + DAP 30 kg + MOP 35 kg + Sulphur 15 kg (Pungency & storage).',
        recommendedFertilizerSummaryHindi: 'यूरिया 45 किलो + डीएपी 30 किलो + पोटाश 35 किलो + सल्फर 15 किलो।',
        simpleAudioHi: 'प्याज़ में सल्फर खाद डालने से कंद का तीखापन और भंडारण क्षमता बढ़ती है। थ्रिप्स कीट के लिए चिपचिपे नीले कार्ड लगाएं।',
        simpleAudioEn: 'Applying sulphur in onions sharpens pungency and shelf life. Use blue sticky traps to monitor onion thrips.',
        iconEmoji: '🧅',
      },
    ],
  },

  // 13. SPICES & CHILLI (मसाले व मिर्च)
  {
    id: 'spices_chilli',
    name: 'Chilli & Spices',
    nameHindi: 'मिर्च व मसाले',
    category: 'spice',
    iconEmoji: '🌶️',
    description: 'High-value spice crops: Guntur Hot Chilli, Kashmiri Mild, Turmeric, Ginger.',
    descriptionHindi: 'गुंटूर तीखी मिर्च, कश्मीरी मिर्च, हल्दी व अदरक।',
    varieties: [
      {
        id: 'chilli_guntur_teja',
        cropFamilyId: 'spices_chilli',
        cropName: 'Chilli & Spices',
        cropHindi: 'मिर्च व मसाले',
        varietyName: 'Hot Red Chilli (Guntur Teja / Byadgi / US-341)',
        varietyHindi: 'तीखी लाल मिर्च (गुंटूर तेजा / ब्यादगी)',
        category: 'spice',
        grainType: 'Slender Hot Fiery Red Pods',
        grainTypeHindi: 'गहरी लाल तीखी मिर्च (उच्च कैप्साइसिन)',
        durationDays: 150,
        waterRequirement: 'Medium',
        waterRequirementHindi: 'मध्यम पानी (ड्रिप सिंचाई अनुकूल)',
        optimalNpkPerAcre: { nitrogenKg: 50, phosphorusKg: 30, potassiumKg: 40 },
        targetYieldQuintalPerAcre: 25, // dry chilli
        commonPests: ['Chilli Thrips (Murda Disease)', 'Mites', 'Anthracnose (Dieback)'],
        commonPestsHindi: ['चुरडा-मुरडा (थ्रिप्स व माइट्स)', 'डाइबैक फफूंद', 'फल सड़न'],
        recommendedFertilizerSummary: 'Urea 50 kg + DAP 30 kg + Potash 40 kg + Micronutrient mix.',
        recommendedFertilizerSummaryHindi: 'यूरिया 50 किलो + डीएपी 30 किलो + पोटाश 40 किलो + सूक्ष्म पोषक तत्व।',
        simpleAudioHi: 'मिर्च में चुरडा-मुरडा रोग थ्रिप्स और मकड़ी से होता है। इसके लिए पीले व नीले कार्ड लगाएं और नीम तेल का छिड़काव करें।',
        simpleAudioEn: 'Chilli leaf curl is triggered by thrips and mites. Maintain regular foliar nutrition and organic neem sprays.',
        iconEmoji: '🌶️',
      },
      {
        id: 'spice_turmeric_salem',
        cropFamilyId: 'spices_chilli',
        cropName: 'Chilli & Spices',
        cropHindi: 'मिर्च व मसाले',
        varietyName: 'Turmeric (Salem / Pragati / Waigaon High Curcumin)',
        varietyHindi: 'हल्दी (सलेम / प्रगति / वाईगांव 6% करक्यूमिन)',
        category: 'spice',
        grainType: 'Bright Orange Thick Rhizome',
        grainTypeHindi: 'गहरा नारंगी कंद (उच्च करक्यूमिन औषधीय हल्दी)',
        durationDays: 240,
        waterRequirement: 'Medium',
        waterRequirementHindi: 'मध्यम पानी (अच्छी जल निकासी)',
        optimalNpkPerAcre: { nitrogenKg: 40, phosphorusKg: 25, potassiumKg: 35 },
        targetYieldQuintalPerAcre: 90,
        commonPests: ['Rhizome Rot (Pythium)', 'Leaf Spot', 'Shoot Borer'],
        commonPestsHindi: ['कंद सड़न रोग', 'पत्ती धब्बा', 'तना छेदक'],
        recommendedFertilizerSummary: 'FYM 3 tons + Urea 40 kg + SSP 60 kg + MOP 35 kg + Trichoderma.',
        recommendedFertilizerSummaryHindi: 'गोबर खाद 3 टन + यूरिया 40 किलो + एसएसपी 60 किलो + पोटाश 35 किलो + ट्राइकोडर्मा।',
        simpleAudioHi: 'हल्दी में कंद सड़न से बचाव के लिए ट्राइकोडर्मा जैविक फफूंदनाशक का प्रयोग करें और खेत में पानी न ठहरने दें।',
        simpleAudioEn: 'For turmeric, blend Trichoderma bio-fungicide into compost to prevent rhizome rot and ensure raised bed drainage.',
        iconEmoji: '🫚',
      },
    ],
  },

  // 14. FRUITS & PLANTATION (फल व बागवानी)
  {
    id: 'fruits',
    name: 'Fruits & Horticulture',
    nameHindi: 'फल व बागवानी',
    category: 'fruit',
    iconEmoji: '🥭',
    description: 'High-value fruit crops: Mango, Banana, Citrus, Apple, Guava.',
    descriptionHindi: 'आम (अल्फांसो, दशहरी), केला (G9), संतरा व सेब।',
    varieties: [
      {
        id: 'fruit_mango_alphonso',
        cropFamilyId: 'fruits',
        cropName: 'Fruits & Horticulture',
        cropHindi: 'फल व बागवानी',
        varietyName: 'Mango (Alphonso / Dasheri / Kesar)',
        varietyHindi: 'आम (अल्फांसो / दशहरी / केसर - फलों का राजा)',
        category: 'fruit',
        grainType: 'Aromatic Sweet Pulp Rich Table Fruit',
        grainTypeHindi: 'मीठा रसीला खुशबूदार गूदा (निर्यात ग्रेड)',
        durationDays: 365,
        waterRequirement: 'Medium',
        waterRequirementHindi: 'मध्यम पानी (मंजरी के समय सिंचाई बंद)',
        optimalNpkPerAcre: { nitrogenKg: 50, phosphorusKg: 30, potassiumKg: 50 },
        targetYieldQuintalPerAcre: 60,
        commonPests: ['Mango Hopper', 'Powdery Mildew', 'Anthracnose', 'Fruit Fly'],
        commonPestsHindi: ['भुनगा कीट (हॉपर)', 'चूर्णिल आसिता (पाउडरी मिल्ड्यू)', 'फल मक्खी'],
        recommendedFertilizerSummary: 'Annual tree basin dose: Urea 500g + DAP 300g + MOP 500g + 20kg Compost per tree.',
        recommendedFertilizerSummaryHindi: 'प्रति पेड़: यूरिया 500 ग्राम + डीएपी 300 ग्राम + पोटाश 500 ग्राम + 20 किलो गोबर खाद।',
        simpleAudioHi: 'आम में बौर (मंजरी) आते समय सिंचाई रोक दें और पाउडरी मिल्ड्यू से बचाव के लिए घुलनशील गंधक का छिड़काव करें।',
        simpleAudioEn: 'In mango orchards, withhold irrigation during flowering and spray wettable sulphur against powdery mildew.',
        iconEmoji: '🥭',
      },
      {
        id: 'fruit_banana_g9',
        cropFamilyId: 'fruits',
        cropName: 'Fruits & Horticulture',
        cropHindi: 'फल व बागवानी',
        varietyName: 'Banana (Grand Naine G-9 Tissue Culture)',
        varietyHindi: 'केला (ग्रैंड नैन G-9 टिश्यू कल्चर)',
        category: 'fruit',
        grainType: 'Uniform Large Export Grade Bunch',
        grainTypeHindi: 'एकसमान लंबा मीठा केला (30-35 किलो का घहर)',
        durationDays: 330,
        waterRequirement: 'High',
        waterRequirementHindi: 'अधिक पानी (ड्रिप फर्टीगेशन)',
        optimalNpkPerAcre: { nitrogenKg: 90, phosphorusKg: 40, potassiumKg: 100 },
        targetYieldQuintalPerAcre: 350,
        commonPests: ['Sigatoka Leaf Spot', 'Panama Wilt (Fusarium)', 'Pseudostem Borer'],
        commonPestsHindi: ['सिगाटोका पत्ती रोग', 'पनामा उकठा', 'तना छेदक'],
        recommendedFertilizerSummary: 'High Potash fertigation: Urea 90 kg + Phosphoric acid + MOP 100 kg per acre.',
        recommendedFertilizerSummaryHindi: 'ड्रिप द्वारा: यूरिया 90 किलो + फास्फोरिक एसिड + पोटाश 100 किलो प्रति एकड़।',
        simpleAudioHi: 'केले में भारी पोटाश की जरूरत होती है जिससे घहर का वजन बढ़ता है। सिगाटोका रोग से पुरानी पत्तियों को काटें।',
        simpleAudioEn: 'Banana requires high potassium fertigation for dense bunches. Prune diseased lower leaves against Sigatoka.',
        iconEmoji: '🍌',
      },
    ],
  },
];

// Flat list of all crop varieties
export const ALL_CROP_VARIETIES: CropVariety[] = GLOBAL_CROP_FAMILIES.flatMap((f) => f.varieties);

// Helper function to get variety by ID
export function getCropVarietyById(id: string): CropVariety {
  const found = ALL_CROP_VARIETIES.find((v) => v.id === id);
  return found || ALL_CROP_VARIETIES[0]; // default to Basmati Rice
}

// Helper to get crop family
export function getCropFamilyById(id: string): CropFamily | undefined {
  return GLOBAL_CROP_FAMILIES.find((f) => f.id === id);
}
